unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g base-index 1
set -g pane-base-index 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-sessionx'

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r '"' split-window -v -c "#{pane_current_path}"
bind-key -r '%' split-window -h -c "#{pane_current_path}"
bind-key -r 'c' new-window -c "#{pane_current_path}"

set -g @plugin 'christoomey/vim-tmux-navigator'

# Uses `fzf --tmux` instead of the `fzf-tmux` script (requires fzf >= 0.53).
set -g @sessionx-fzf-builtin-tmux 'on'

# Window mode can be turned on so that the default layout
# Has all the windows listed rather than sessions only
set -g @sessionx-window-mode 'on'

# When set to 'on' a non-result will be sent to zoxide for path matching
# Requires zoxide installed
set -g @sessionx-zoxide-mode 'on'

# catppuccin configurations
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'


# catppuccin conf
#set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_middle_separator ""
set -g @catppuccin_window_right_separator ""

set -g @catppuccin_window_flags ""
set -g @catppuccin_window_number ""

set -g @catppuccin_window_current_number_color "#{@thm_flamingo}"
set -g @catppuccin_window_current_number "#[bg=#{@thm_bg},fg=#{@thm_flamingo}] #I:"
set -g @catppuccin_window_current_text "#[bg=#{@thm_bg},fg=#{@thm_flamingo}]#{?#{!=:#{window_name},},#W,}"

set -g @catppuccin_window_number_color "#{@thm_bg}"
set -g @catppuccin_window_number "#[bg=#{@thm_bg},fg=#{@thm_subtext_1}] #I :"
set -g @catppuccin_window_text "#[bg=#{@thm_bg},fg=#{@thm_subtext_1}]#{?#{!=:#{window_name},},#W,}"

set -g @catppuccin_window_flags "icon"


# tmux conf
set-option -g status-position top
#set -g status-style "bg=#{@thm_bg}"
set -g status-style 'bg=terminal'

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
# set -g status-right-length 100
set -g status-right ""
# set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# window style
set -g status-justify 'right'
set -wg automatic-rename on
# set -g automatic-rename-format ''
set -g window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none] │ "


set -g pane-border-format ""
set -g pane-border-status top
set -g pane-border-style fg=colour0
set -g pane-active-border-style fg=colour0


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

